// ─── Data & Constants ─────────────────────────────────────────────────────────

export const SEASONS = [
  { key: "dry",       label: "Dry Season",     sub: "Dec – Mar", icon: "☀️", color: "#F59E0B" },
  { key: "inter1",    label: "Inter-monsoon",   sub: "Apr – May", icon: "🌤", color: "#10B981" },
  { key: "swmonsoon", label: "SW Monsoon",      sub: "Jun – Sep", icon: "🌧", color: "#3B82F6" },
  { key: "inter2",    label: "NE Monsoon",      sub: "Oct – Nov", icon: "🌦", color: "#8B5CF6" },
];

export const MOODS = [
  { key: "adventure", icon: "🏔", label: "Adventure" },
  { key: "romantic",  icon: "💑", label: "Romantic"  },
  { key: "family",    icon: "👨‍👩‍👧", label: "Family"    },
  { key: "scenic",    icon: "🌅", label: "Scenic"    },
  { key: "cultural",  icon: "🛕", label: "Cultural"  },
  { key: "wildlife",  icon: "🐘", label: "Wildlife"  },
];

export const EVENTS = [
  { key: "Esala Perahera",     icon: "🎆", date: "Jul – Aug"  },
  { key: "Sinhala New Year",   icon: "🌺", date: "Apr 13–14"  },
  { key: "Whale Watch Season", icon: "🐋", date: "Nov – Apr"  },
  { key: "Yala Safari Season", icon: "🐆", date: "Feb – Jul"  },
  { key: "Elephant Gathering", icon: "🐘", date: "Aug – Oct"  },
  { key: "Surf Season",        icon: "🏄", date: "Apr – Oct"  },
  { key: "Nuwara Eliya Season",icon: "🍃", date: "Mar – Apr"  },
  { key: "Trinco Beach Fest",  icon: "🏖", date: "May – Sep"  },
];

export const PIN_COLORS = [
  "#00b0a5", "#378ADD", "#D4537E", "#C49A3C",
  "#7F77DD", "#D85A30", "#639922", "#993556",
  "#185FA5", "#854F0B", "#3B6D11", "#534AB7",
];

export const INIT_LOCS = [
  { id:1,  name:"Colombo",      region:"Western Province",   col:"#378ADD", lat:6.9271, lng:79.8612, desc:"Commercial capital, city tours.",         photos:28 },
  { id:2,  name:"Kandy",        region:"Central Province",   col:"#D4537E", lat:7.2906, lng:80.6337, desc:"Cultural capital, Temple of the Tooth.",   photos:22 },
  { id:3,  name:"Sigiriya",     region:"Cultural Triangle",  col:"#C49A3C", lat:7.9570, lng:80.7603, desc:"Ancient rock fortress, UNESCO site.",      photos:19 },
  { id:4,  name:"Galle",        region:"Southern Province",   col:"#00b0a5", lat:6.0535, lng:80.2210, desc:"Dutch colonial fort city.",                photos:17 },
  { id:5,  name:"Ella",         region:"Uva Province",       col:"#7F77DD", lat:6.8667, lng:81.0466, desc:"Nine Arch Bridge and hill hiking.",        photos:14 },
  { id:6,  name:"Nuwara Eliya", region:"Central Province",   col:"#D85A30", lat:6.9497, lng:80.7891, desc:"Tea highlands, Little England of SL.",    photos:12 },
  { id:7,  name:"Yala",         region:"Southern Province",   col:"#639922", lat:6.3728, lng:81.5222, desc:"Wildlife park, leopard sightings.",        photos:11 },
  { id:8,  name:"Mirissa",      region:"Southern Province",   col:"#993556", lat:5.9483, lng:80.4716, desc:"Whale watching, beach resort.",            photos:10 },
  { id:9,  name:"Trincomalee",  region:"Eastern Province",   col:"#185FA5", lat:8.5922, lng:81.2152, desc:"Natural harbour, white beaches.",          photos:7  },
  { id:10, name:"Arugam Bay",   region:"Eastern Province",   col:"#854F0B", lat:6.8442, lng:81.8358, desc:"World-class surfing east coast.",          photos:6  },
  { id:11, name:"Dambulla",     region:"Cultural Triangle",  col:"#3B6D11", lat:7.8742, lng:80.6511, desc:"Cave temple, 150 Buddha statues.",         photos:5  },
  { id:12, name:"Pinnawala",    region:"Sabaragamuwa",       col:"#534AB7", lat:7.2993, lng:80.3831, desc:"Elephant orphanage, river bathing.",       photos:4  },
];

export const SAMPLE_PHOTOS = [
  { 
    id: 1,  
    title: "Sigiriya Sunrise Summit",    
    emoji: "🦅", 
    image: "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "adventure", 
    loc: "Sigiriya",     
    event: "Sinhala New Year",   
    status: "published",
    tourist: "Priya & Rohan",
    date: "2026-03-12",
    desc: "A breathtaking sunrise view from the ancient sky palace of King Kasyapa. The morning mist hugging the forest looked magical.",
    tags: ["Sigiriya", "fortress", "sunrise", "hiking", "heritage"],
    withTourists: true
  },
  { 
    id: 2,  
    title: "Kandy Temple & Lake Drive",      
    emoji: "🎆", 
    image: "https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=800&q=80",
    season: "swmonsoon", 
    mood: "cultural",  
    loc: "Kandy",        
    event: "Esala Perahera",     
    status: "published",
    tourist: "Alice & Mark",
    date: "2025-08-15",
    desc: "Visiting the sacred Temple of the Tooth Relic in the evening. The local guide took us to a secret viewpoint overlooking Kandy lake.",
    tags: ["Kandy", "temple", "lake", "culture", "monsoon"],
    withTourists: false
  },
  { 
    id: 3,  
    title: "Mirissa Blue Whale Safari",      
    emoji: "🐋", 
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "wildlife",  
    loc: "Mirissa",      
    event: "Whale Watch Season", 
    status: "published",
    tourist: "The Miller Family",
    date: "2026-01-20",
    desc: "We saw three blue whales and a huge pod of spinner dolphins playing in the wake of our boat. Truly an unforgettable wildlife cruise.",
    tags: ["Mirissa", "whales", "safari", "ocean", "beach"],
    withTourists: true
  },
  { 
    id: 4,  
    title: "Nine Arch Bridge Blue Train",    
    emoji: "🌉", 
    image: "https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=800&q=80",
    season: "inter1",    
    mood: "scenic",    
    loc: "Ella",         
    event: "Surf Season",                 
    status: "published",
    tourist: "Jack & Emily",
    date: "2025-05-04",
    desc: "Our driver timed our arrival perfectly with the morning train crossing. A beautiful architectural feat amidst green mountains.",
    tags: ["Ella", "bridge", "train", "scenic", "mountains"],
    withTourists: false
  },
  { 
    id: 5,  
    title: "Yala Leopard Tracking Safari", 
    emoji: "🐆", 
    image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "wildlife",  
    loc: "Yala",         
    event: "Yala Safari Season", 
    status: "draft",
    tourist: "David & Sarah",
    date: "2026-02-18",
    desc: "Witnessed this magnificent Sri Lankan leopard lounge gracefully on a branch in Zone 1. Our driver's tracking skills were stellar.",
    tags: ["Yala", "leopard", "wildlife", "safari", "national park"],
    withTourists: true
  },
  { 
    id: 6,  
    title: "Galle Fort Lighthouse Sunset",   
    emoji: "🏰", 
    image: "https://images.unsplash.com/photo-1563294863-bd43ca860bc2?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "romantic",  
    loc: "Galle",        
    event: "Trinco Beach Fest",                 
    status: "published",
    tourist: "Elena & Luca",
    date: "2026-02-05",
    desc: "Strolling the centuries-old ramparts of Galle Dutch Fort as local kids flew kites against the orange sky. Feels straight out of a postcard.",
    tags: ["Galle", "fort", "sunset", "lighthouse", "coastal"],
    withTourists: false
  },
  { 
    id: 7,  
    title: "Nuwara Eliya Tea Plucking",    
    emoji: "🍃", 
    image: "https://images.unsplash.com/photo-1555899434-94d1368aa712?auto=format&fit=crop&w=800&q=80",
    season: "inter1",    
    mood: "scenic",    
    loc: "Nuwara Eliya", 
    event: "Nuwara Eliya Season",
    status: "published",
    tourist: "Takahiro & Yuki",
    date: "2025-04-10",
    desc: "Learned about the intensive tea production process, starting from the green slopes and ending with a delicious tea tasting session.",
    tags: ["Nuwara Eliya", "tea", "highlands", "plantations", "scenic"],
    withTourists: true
  },
  { 
    id: 8,  
    title: "Pinnawala Elephants Bathing",      
    emoji: "🐘", 
    image: "https://images.unsplash.com/photo-1585938338392-50a59910d6e5?auto=format&fit=crop&w=800&q=80",
    season: "swmonsoon", 
    mood: "family",    
    loc: "Pinnawala",    
    event: "Elephant Gathering", 
    status: "draft",
    tourist: "The Anderson Family",
    date: "2025-07-22",
    desc: "Sitting by the river cafe while dozens of elephants splashed in the water to cool off. The kids absolutely loved feeding the baby elephants.",
    tags: ["Pinnawala", "elephants", "river", "family", "bathing"],
    withTourists: false
  },
  { 
    id: 9,  
    title: "Colombo Skyline & Sea Walk", 
    emoji: "🌆", 
    image: "https://images.unsplash.com/photo-1588598126714-c689d060fb86?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "romantic",  
    loc: "Colombo",      
    event: null,                 
    status: "published",
    tourist: "Nisha & Karan",
    date: "2026-03-01",
    desc: "A lovely night walk around Galle Face Green, with the futuristic skyline rising in the background against the warm Indian Ocean breeze.",
    tags: ["Colombo", "city", "skyline", "night", "coast"],
    withTourists: true
  },
  { 
    id: 10, 
    title: "Arugam Bay Surf Camp",  
    emoji: "🏄", 
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80",
    season: "swmonsoon", 
    mood: "adventure", 
    loc: "Arugam Bay",   
    event: "Surf Season",        
    status: "published",
    tourist: "Sven & Chloe",
    date: "2025-07-02",
    desc: "Great waves at Main Point today! Met surfers from all around the world and chilled at the beach shack for some fresh mango smoothies.",
    tags: ["Arugam Bay", "surf", "beach", "waves", "adventure"],
    withTourists: false
  },
  { 
    id: 11, 
    title: "Dambulla Cave Golden Temple",
    emoji: "🕯", 
    image: "https://images.unsplash.com/photo-1608958416738-9577f884a4ec?auto=format&fit=crop&w=800&q=80",
    season: "dry",       
    mood: "cultural",  
    loc: "Dambulla",     
    event: "Sinhala New Year",   
    status: "published",
    tourist: "Arthur & Marion",
    date: "2026-01-14",
    desc: "Unbelievable rock temple carved into cliffs. Entering the dark caves and seeing 150 Buddha statues illuminated by oil lamps felt mystical.",
    tags: ["Dambulla", "caves", "temple", "buddha", "culture"],
    withTourists: true
  },
  { 
    id: 12, 
    title: "Trincomalee Nilaveli Family Trip", 
    emoji: "🏖", 
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80",
    season: "inter2",    
    mood: "family",    
    loc: "Trincomalee",  
    event: "Trinco Beach Fest",  
    status: "draft",
    tourist: "The Dubois Family",
    date: "2025-10-18",
    desc: "Perfect white-sand beaches at Nilaveli. Took a boat trip to Pigeon Island for some unbelievable coral reef snorkeling with turtles.",
    tags: ["Trinco", "beach", "snorkeling", "family", "resort"],
    withTourists: false
  },
];

export const EMOJIS = ["🌴","🦅","🐘","🌺","🛕","🏔","🌅","🌊","🐆","🍃","🏖","🌉"];

export const TOUR_PRESETS = [
  {
    title: "Sigiriya Fortress Vista",
    image: "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80",
    season: "dry",
    mood: "adventure",
    loc: "Sigiriya",
    event: "Sinhala New Year",
    desc: "A stunning morning climb of the eighth wonder of the world. Clear blue skies with unmatched 360-degree views of the archaeological park.",
    tourist: "Rohan & Meera",
    tags: ["Sigiriya", "fortress", "ancient", "climb", "UNESCO"],
    lat: "7.9570",
    lng: "80.7603"
  },
  {
    title: "Ella Nine Arch Bridge Train",
    image: "https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=800&q=80",
    season: "inter1",
    mood: "scenic",
    loc: "Ella",
    event: "Surf Season",
    desc: "Stunning shot of the world-famous blue train crossing the Nine Arch Bridge, surrounded by deep forests and sprawling green tea gardens.",
    tourist: "Sophia & Alex",
    tags: ["Ella", "nine arches", "railway", "hill country", "tea"],
    lat: "6.8667",
    lng: "81.0466"
  },
  {
    title: "Galle Dutch Fort Lighthouse",
    image: "https://images.unsplash.com/photo-1563294863-bd43ca860bc2?auto=format&fit=crop&w=800&q=80",
    season: "dry",
    mood: "romantic",
    loc: "Galle",
    event: null,
    desc: "Chasing sunsets along the historical brick ramparts of Galle Fort. Cobblestone streets, ancient churches, and lovely coastlines.",
    tourist: "Markus & Ingrid",
    tags: ["Galle", "fortress", "lighthouse", "colonial", "coastal"],
    lat: "6.0535",
    lng: "80.2210"
  },
  {
    title: "Yala Majestic Leopard Safari",
    image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
    season: "dry",
    mood: "wildlife",
    loc: "Yala",
    event: "Yala Safari Season",
    desc: "Spotted this legendary predator in Yala Block 1 during golden hour. A stunning big cat looking straight into our cameras.",
    tourist: "Hans & Lisa",
    tags: ["Yala", "safari", "leopard", "national park", "wildlife"],
    lat: "6.3728",
    lng: "81.5222"
  },
  {
    title: "Nuwara Eliya Highlands Tea Estate",
    image: "https://images.unsplash.com/photo-1555899434-94d1368aa712?auto=format&fit=crop&w=800&q=80",
    season: "inter1",
    mood: "scenic",
    loc: "Nuwara Eliya",
    event: "Nuwara Eliya Season",
    desc: "Plucking tea with local harvesters, wandering through clouds at 1800m elevation. Beautiful colonial-style bungalow gardens.",
    tourist: "Hiroshi & Saki",
    tags: ["Nuwara Eliya", "tea", "estate", "ceylon", "hills"],
    lat: "6.9497",
    lng: "80.7891"
  },
  {
    title: "Mirissa Golden Palm Coastline",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    season: "dry",
    mood: "romantic",
    loc: "Mirissa",
    event: "Whale Watch Season",
    desc: "Warm water, palm tree swing, and absolute beach paradise in South Sri Lanka. A romantic walk along the turquoise reef.",
    tourist: "Jessica & Pierre",
    tags: ["Mirissa", "beach", "coastline", "surf", "tropical"],
    lat: "5.9483",
    lng: "80.4716"
  }
];